In [82]:
import pandas as pd


SEED = 42


def print_memory_usage(df: pd.DataFrame) -> None:
    print(f"{df.memory_usage(deep=True).sum() / 1024**2} mb\n")
    return None

In [83]:
rating = pd.read_csv(
    "../data/raw/ml-25m/ratings.csv",
)
print(rating.dtypes)
print_memory_usage(rating)

userId         int64
movieId        int64
rating       float64
timestamp      int64
dtype: object
762.9424781799316 mb

In [84]:
rating = rating.astype(
    {
        'movieId': 'int32',
        'rating': 'float32',
        'userId': 'int32'
    }
)
rating['timestamp'] = pd.to_datetime(
    rating['timestamp'],
    unit='s'
)

In [85]:
print(rating.dtypes)
print_memory_usage(rating)

userId               int32
movieId              int32
rating             float32
timestamp    datetime64[s]
dtype: object
476.83909606933594 mb

In [86]:
rating.to_parquet("../data/processed/rating.parquet")

del rating

In [87]:
movies = pd.read_csv(
    "../data/raw/ml-25m/movies.csv",
)
movies

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama

In [88]:
print_memory_usage(movies)
movies.to_parquet("../data/processed/movies.parquet")

del movies

3.7449827194213867 mb

In [89]:
df = pd.read_csv(
    "../data/raw/ml-25m/tags.csv",
)
df

         userId  movieId                  tag   timestamp
0             3      260              classic  1439472355
1             3      260               sci-fi  1439472256
2             4     1732          dark comedy  1573943598
3             4     1732       great dialogue  1573943604
4             4     7569     so bad it's good  1573943455
...         ...      ...                  ...         ...
1093355  162521    66934  Neil Patrick Harris  1427311611
1093356  162521   103341     cornetto trilogy  1427311259
1093357  162534   189169               comedy  1527518175
1093358  162534   189169             disabled  1527518181
1093359  162534   189169              robbery  1527518193

[1093360 rows x 4 columns]

In [90]:
df = df.astype(
    {
        'movieId': 'int32',
        'userId': 'int32'
    }
)
df['timestamp'] = pd.to_datetime(
    df['timestamp'], unit='s'
)
df

         userId  movieId                  tag           timestamp
0             3      260              classic 2015-08-13 13:25:55
1             3      260               sci-fi 2015-08-13 13:24:16
2             4     1732          dark comedy 2019-11-16 22:33:18
3             4     1732       great dialogue 2019-11-16 22:33:24
4             4     7569     so bad it's good 2019-11-16 22:30:55
...         ...      ...                  ...                 ...
1093355  162521    66934  Neil Patrick Harris 2015-03-25 19:26:51
1093356  162521   103341     cornetto trilogy 2015-03-25 19:20:59
1093357  162534   189169               comedy 2018-05-28 14:36:15
1093358  162534   189169             disabled 2018-05-28 14:36:21
1093359  162534   189169              robbery 2018-05-28 14:36:33

[1093360 rows x 4 columns]

In [91]:
print_memory_usage(df)
df.to_parquet("../data/processed/tags.parquet")

del df

36.2772216796875 mb

In [92]:
df = pd.read_csv(
    "../data/raw/ml-25m/genome-scores.csv",
)
df

          movieId  tagId  relevance
0               1      1    0.02875
1               1      2    0.02375
2               1      3    0.06250
3               1      4    0.07575
4               1      5    0.14075
...           ...    ...        ...
15584443   206499   1124    0.11000
15584444   206499   1125    0.04850
15584445   206499   1126    0.01325
15584446   206499   1127    0.14025
15584447   206499   1128    0.03350

[15584448 rows x 3 columns]

In [93]:
df = df.astype(
    {
        'movieId': 'int32',
        'tagId': 'int16',
        'relevance': 'float32'
    }
)
df

          movieId  tagId  relevance
0               1      1    0.02875
1               1      2    0.02375
2               1      3    0.06250
3               1      4    0.07575
4               1      5    0.14075
...           ...    ...        ...
15584443   206499   1124    0.11000
15584444   206499   1125    0.04850
15584445   206499   1126    0.01325
15584446   206499   1127    0.14025
15584447   206499   1128    0.03350

[15584448 rows x 3 columns]

In [94]:
print_memory_usage(df)
df.to_parquet("../data/processed/genome-scores.parquet")

del df

148.62500381469727 mb

In [95]:
df = pd.read_csv(
    "../data/raw/ml-25m/genome-tags.csv",
)
df

      tagId           tag
0         1           007
1         2  007 (series)
2         3  18th century
3         4         1920s
4         5         1930s
...     ...           ...
1123   1124       writing
1124   1125         wuxia
1125   1126          wwii
1126   1127        zombie
1127   1128       zombies

[1128 rows x 2 columns]

In [96]:
print_memory_usage(df)
df.to_parquet("../data/processed/genome-tags.parquet")

del df

0.02811717987060547 mb